name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -S ${GITHUB_WORKSPACE} -B ${GITHUB_WORKSPACE}/build -G "Unix Makefiles" -D CMAKE_C_COMPILER="/usr/bin/clang" "$@"

    - name: Build
      run: cmake --build ${GITHUB_WORKSPACE}/build

    - name: Test
      run: ctest --test-dir ${GITHUB_WORKSPACE}/build/


